### ISSUE TITLE
Autofill Offset evaluation Improvement

### ISSUE THREAD

**Issue by sinsalabim** [codingdna2/WpfDxfViewer#1]
The AutoFill() method of the MainWindow should apply the ZoomableCanvas.Layout.Transform to the Evaluated offset at line 375 in MainWindow.xaml.cs
If you reverse axis orientation via ScaleTransform ScaleY="-1", you have to apply the same matrix transformation to the new ZoomableCanvas.Offset

Hence it should be:

Point rawOffset = new System.Windows.Point(minLeft * scale - (canvas.ActualWidth - (maxLeft - minLeft) * scale) / 2, minTop * scale - (canvas.ActualHeight - ((maxTop - minTop) * scale)) / 2);

canvas.Offset = canvas.LayoutTransform.Transform(rawOffset);

**Comment by codingdna2** [comment]
Hi there, thanks for the fix. 
Can you post a Pull Request?
Regards,
D.
